var initiativeData = [
    // 1. SALES AGENT ENABLEMENT - in NOW backlog
    { id: 1, title: "Effortless Info Access", flag: "", theme: "1. SALES AGENT ENABLEMENT", initiativeType: "CX", journeyStage: "Sales Pre-Qual", description: "Currently, agents must navigate multiple tools and systems to find answers, causing delays and callbacks. This envisions a streamlined way for agents to quickly access and share accurate information during customer conversations.", implementation: "Knowledge base/FAQ", column: "now", requiresTech: false, priority: "tbd" },
    { id: 2, title: "Instant Technical Answers", flag: "", theme: "1. SALES AGENT ENABLEMENT", initiativeType: "CX", journeyStage: "Sales Pre-Qual", description: "Today, agents often have to put customers on hold or call back after verifying technical details. Empowering agents with decision authority and instant access to technical information eliminates this friction.", implementation: "Empower with decision authority", column: "now", requiresTech: false, priority: "tbd" },
    { id: 3, title: "Trip Charge Visibility", flag: "", theme: "1. SALES AGENT ENABLEMENT", initiativeType: "CX", journeyStage: "Sales Pre-Qual", description: "Some customer locations require special 'trip' charges due to distance. Making this visible upfront helps agents set proper expectations and avoid surprises for customers later.", implementation: "Expose existing data", column: "now", requiresTech: false, priority: "tbd" },
    { id: 4, title: "Install Process Guide", flag: "", theme: "1. SALES AGENT ENABLEMENT", initiativeType: "CX", journeyStage: "Sale Occurs", description: "Sales agents often don't fully understand what happens during installation. A clear guide helps them set accurate customer expectations about the installation process, timing, and what the technician will do.", implementation: "Training documentation", column: "now", requiresTech: false, priority: "tbd" },
    { id: 5, title: "Remote Location Flags", flag: "", theme: "1. SALES AGENT ENABLEMENT", initiativeType: "CX", journeyStage: "Sale Occurs", description: "Remote locations have different service availability. Flagging these in Salesforce prevents selling services that can't actually be delivered in certain areas.", implementation: "Salesforce configuration", column: "now", requiresTech: true, priority: "tbd" },
    { id: 6, title: "Construction Delay Alerts", flag: "Proactive touchpoints between sale and install", theme: "1. SALES AGENT ENABLEMENT", initiativeType: "CX", journeyStage: "Sale Occurs", description: "Fiber construction timelines often slip. Proactively notifying sales when delays occur allows them to reach out to waiting customers rather than leaving them in the dark.", implementation: "Notification workflow", column: "scoping", requiresTech: true, priority: "tbd" },
    { id: 7, title: "Ghosting Missed Install Notification", flag: "Ghosting", theme: "1. SALES AGENT ENABLEMENT", initiativeType: "CX", journeyStage: "Sale Occurs", description: "When an installation doesn't happen as scheduled, the sales agent who made the sale should know so they can follow up with the customer and maintain the relationship.", implementation: "Simple alert", column: "scoping", requiresTech: true, priority: "high" },
    
    // 2. BILLING TRANSPARENCY - IMMEDIATE - in NOW backlog
    { id: 8, title: "Full Quote Upfront", flag: "", theme: "2. BILLING TRANSPARENCY - IMMEDIATE", initiativeType: "CX", journeyStage: "Sale Occurs", description: "Customers want to know the total cost before committing-not just the monthly rate, but all one-time charges, taxes, and fees. A complete 'bottom line' quote builds trust.", implementation: "Sales process/template", column: "now", requiresTech: false, priority: "tbd" },
    { id: 9, title: "Bill Breakdown Email", flag: "", theme: "2. BILLING TRANSPARENCY - IMMEDIATE", initiativeType: "CX", journeyStage: "Sale Occurs", description: "After a sales call, customers receive an email clearly breaking down what their first bill will look like, what one-time charges apply, and what their ongoing monthly bill will be.", implementation: "Email template", column: "now", requiresTech: true, priority: "tbd" },
    { id: 10, title: "Bill Preview Mock-up", flag: "", theme: "2. BILLING TRANSPARENCY - IMMEDIATE", initiativeType: "CX", journeyStage: "Sale Occurs", description: "Visual mock-ups of the actual first and second bills help customers understand exactly what to expect. The first bill is often confusing with partial months and setup fees.", implementation: "Bill preview template", column: "now", requiresTech: true, priority: "tbd" },
    { id: 11, title: "Price Guarantee", flag: "", theme: "2. BILLING TRANSPARENCY - IMMEDIATE", initiativeType: "CX", journeyStage: "Sale Occurs", description: "Customers should receive exactly what was promised during the sale-no unexpected changes to pricing or packages between order and activation.", implementation: "Process discipline", column: "now", requiresTech: false, priority: "tbd" },
    { id: 12, title: "Promise Delivery", flag: "", theme: "2. BILLING TRANSPARENCY - IMMEDIATE", initiativeType: "CX", journeyStage: "Sale Occurs", description: "This is the fundamental promise: what was sold is what gets delivered. Product specs, pricing, promotional rates, and installation timelines should all match.", implementation: "Accountability process", column: "now", requiresTech: false, priority: "tbd" },
    
    // 2. SERVICEABILITY & COVERAGE TOOLS - in Scoping
    { id: 13, title: "Usage Needs Assessment", flag: "Structured pre-qual", theme: "2. SERVICEABILITY & COVERAGE TOOLS", initiativeType: "CX", journeyStage: "Sales Pre-Qual", description: "Brief questions about how the customer uses internet helps agents recommend the right package size.", implementation: "Needs assessment tool", column: "scoping", requiresTech: true, priority: "tbd" },
    
    // 3. EXPECTATION SETTING & COMMUNICATION BASICS
    { id: 14, title: "Next Steps Clarity", flag: "Prepare for install", theme: "3. EXPECTATION SETTING & COMMUNICATION BASICS", initiativeType: "CX", journeyStage: "Sale Occurs", description: "After the sale, customers should clearly understand: when installation will happen, what their bills will look like, and what they need to do before the technician arrives.", implementation: "Process change - no tech needed", column: "scoping", requiresTech: false, priority: "tbd" },
    { id: 15, title: "Install Day Expectations", flag: "Prepare for install", theme: "3. EXPECTATION SETTING & COMMUNICATION BASICS", initiativeType: "CX", journeyStage: "Installation is Booked", description: "Customers should know exactly what installation day looks like: how long it takes, what the technician will do, what areas of the home they'll access.", implementation: "Create standard communication template", column: "scoping", requiresTech: false, priority: "tbd" },
    { id: 16, title: "Scheduling Difficulty Alert", flag: "Proactive touchpoints between sale and install", theme: "3. EXPECTATION SETTING & COMMUNICATION BASICS", initiativeType: "CX", journeyStage: "Installation is Booked", description: "If scheduling is challenging due to availability or capacity, customers should be notified immediately rather than left waiting.", implementation: "Can be done with existing tools", column: "scoping", requiresTech: false, priority: "tbd" },
    { id: 17, title: "Landlord Approval Reminder", flag: "Prepare for install", theme: "3. EXPECTATION SETTING & COMMUNICATION BASICS", initiativeType: "CX", journeyStage: "Installation is Booked", description: "Many installations require landlord or building manager approval. A timely reminder helps customers get this sorted before the technician arrives.", implementation: "Simple automated reminder", column: "scoping", requiresTech: true, priority: "tbd" },
    { id: 18, title: "On-Site Time Estimate", flag: "", theme: "3. EXPECTATION SETTING & COMMUNICATION BASICS", initiativeType: "CX", journeyStage: "Installation is Booked", description: "Before starting work, the technician explains what they'll be doing, approximately how long it will take, and what the customer can expect.", implementation: "Training/process change", column: "now", requiresTech: false, priority: "tbd" },
    { id: 19, title: "Change Approval Process", flag: "", theme: "3. EXPECTATION SETTING & COMMUNICATION BASICS", initiativeType: "CX", journeyStage: "Installation is Booked", description: "If the technician discovers something different than expected, they get customer approval before proceeding rather than making unilateral decisions.", implementation: "Training/process change", column: "now", requiresTech: false, priority: "tbd" },
    { id: 20, title: "Pre-Install Walkthrough", flag: "", theme: "3. EXPECTATION SETTING & COMMUNICATION BASICS", initiativeType: "CX", journeyStage: "Installation Occurs", description: "The technician does a walkthrough with the customer showing: where equipment will go, where any holes or cabling will run, and how router/cubes will provide coverage.", implementation: "Training/checklist", column: "now", requiresTech: false, priority: "tbd" },
    { id: 21, title: "Pre-Service Report", flag: "", theme: "3. EXPECTATION SETTING & COMMUNICATION BASICS", initiativeType: "CX", journeyStage: "Installation Occurs", description: "Before starting, the technician documents the planned installation in a Pre-Service Report and reviews it with the customer.", implementation: "Process enhancement", column: "now", requiresTech: false, priority: "tbd" },
    
    // 3. PAYMENT & ACTIVATION STREAMLINING - in Scoping
    { id: 22, title: "QR Code Activation", flag: "Simplified activation process", theme: "3. PAYMENT & ACTIVATION STREAMLINING", initiativeType: "CX", journeyStage: "Account is Activated", description: "The technician provides a QR code that customers scan to quickly access their account and setup guides.", implementation: "Digital handoff", column: "scoping", requiresTech: true, priority: "tbd" },
    
    // 4. TECHNICIAN QUALITY & CONSISTENCY - in NOW backlog
    { id: 23, title: "Consistent Branding", flag: "", theme: "4. TECHNICIAN QUALITY & CONSISTENCY", initiativeType: "CX", journeyStage: "Installation Occurs", description: "Whether it's a Canada Connects technician or an integrated technician, they should all look like Xplore. Consistent branding creates a professional impression.", implementation: "Uniform/branding standards", column: "now", requiresTech: false, priority: "tbd" },
    { id: 24, title: "Tech ID Badges", flag: "", theme: "4. TECHNICIAN QUALITY & CONSISTENCY", initiativeType: "CX", journeyStage: "Installation Occurs", description: "Every technician should wear visible Xplore identification. This helps customers feel safe letting someone into their home.", implementation: "Policy enforcement", column: "now", requiresTech: false, priority: "tbd" },
    { id: 25, title: "Branded Swag Leave-Behind", flag: "", theme: "4. TECHNICIAN QUALITY & CONSISTENCY", initiativeType: "CX", journeyStage: "Installation Occurs", description: "Small branded items left with the customer serve as both a thank-you gesture and ongoing brand reminder in the home.", implementation: "Procurement/logistics", column: "now", requiresTech: false, priority: "tbd" },
    { id: 26, title: "Pet Treats", flag: "", theme: "4. TECHNICIAN QUALITY & CONSISTENCY", initiativeType: "CX", journeyStage: "Installation Occurs", description: "A simple gesture that shows care for the whole household. Technicians carrying pet treats can quickly make friends with family pets.", implementation: "Simple customer delight", column: "now", requiresTech: false, priority: "tbd" },
    { id: 27, title: "WiFi Info Card", flag: "", theme: "4. TECHNICIAN QUALITY & CONSISTENCY", initiativeType: "CX", journeyStage: "Installation Occurs", description: "A card left behind with WiFi network name, password, basic tips gives customers a handy reference after the technician leaves.", implementation: "Print collateral", column: "now", requiresTech: false, priority: "tbd" },
    { id: 28, title: "Walk-Out Checklist", flag: "", theme: "4. TECHNICIAN QUALITY & CONSISTENCY", initiativeType: "CX", journeyStage: "Installation Occurs", description: "Before leaving, the technician and customer go through a checklist together: WiFi working? TV working? Customer knows how to use everything?", implementation: "Paper checklist first", column: "now", requiresTech: false, priority: "tbd" },
    { id: 29, title: "Speed Test Demo", flag: "", theme: "4. TECHNICIAN QUALITY & CONSISTENCY", initiativeType: "CX", journeyStage: "Installation Occurs", description: "The technician runs a speed test while the customer watches, showing them the actual speeds they're getting.", implementation: "Training/process", column: "now", requiresTech: false, priority: "tbd" },
    { id: 30, title: "Live Service Test", flag: "", theme: "4. TECHNICIAN QUALITY & CONSISTENCY", initiativeType: "CX", journeyStage: "Installation Occurs", description: "Before the technician leaves, the customer actually uses their new service-browses the web, starts a download, streams a video.", implementation: "Training/process", column: "now", requiresTech: false, priority: "tbd" },
    { id: 31, title: "Signal Stability Check", flag: "", theme: "4. TECHNICIAN QUALITY & CONSISTENCY", initiativeType: "CX", journeyStage: "Installation Occurs", description: "For Fixed Wireless installations, the signal needs to be tested for stability over time, not just a quick snapshot.", implementation: "Extended testing protocol", column: "now", requiresTech: false, priority: "tbd" },
    { id: 32, title: "Whole-Home WiFi Test", flag: "", theme: "4. TECHNICIAN QUALITY & CONSISTENCY", initiativeType: "CX", journeyStage: "Installation Occurs", description: "The technician tests WiFi connectivity in different rooms to ensure coverage throughout the home.", implementation: "Training/checklist", column: "now", requiresTech: false, priority: "tbd" },
    { id: 33, title: "TV Service Demo", flag: "", theme: "4. TECHNICIAN QUALITY & CONSISTENCY", initiativeType: "CX", journeyStage: "Installation Occurs", description: "If the customer has TV service, the technician demonstrates how to use it so the customer feels confident.", implementation: "Training requirement", column: "now", requiresTech: false, priority: "tbd" },
    { id: 34, title: "Phone Test Call", flag: "", theme: "4. TECHNICIAN QUALITY & CONSISTENCY", initiativeType: "CX", journeyStage: "Installation Occurs", description: "For customers with Xplore Home Phone service, the technician makes a test call to verify the phone works properly.", implementation: "Training requirement", column: "now", requiresTech: false, priority: "tbd" },
    { id: 35, title: "Remote Programming", flag: "", theme: "4. TECHNICIAN QUALITY & CONSISTENCY", initiativeType: "CX", journeyStage: "Installation Occurs", description: "The technician programs the remote to work with the customer's TV, so they can control volume and power without multiple remotes.", implementation: "Training requirement", column: "now", requiresTech: false, priority: "tbd" },
    { id: 36, title: "Tech Recognition Program", flag: "", theme: "4. TECHNICIAN QUALITY & CONSISTENCY", initiativeType: "CX", journeyStage: "Installation Occurs", description: "Instead of only hearing about problems, technicians should be recognized when they deliver excellent service.", implementation: "Recognition program", column: "now", requiresTech: false, priority: "tbd" },
    
    // 5. DATA CAPTURE FOR FUTURE AUTOMATION - in NOW backlog
    { id: 37, title: "Voice-to-Text Notes", flag: "", theme: "5. DATA CAPTURE FOR FUTURE AUTOMATION", initiativeType: "CX", journeyStage: "Installation Occurs", description: "Technicians are often outside in cold weather with frozen fingers trying to type notes. Voice-to-text allows them to speak naturally.", implementation: "Enable existing capability", column: "now", requiresTech: true, priority: "tbd" },
    { id: 38, title: "Easy Photo Documentation", flag: "", theme: "5. DATA CAPTURE FOR FUTURE AUTOMATION", initiativeType: "CX", journeyStage: "Installation Occurs", description: "Easy documentation tools let technicians quickly capture photos and notes that automatically sync to the customer's account.", implementation: "FSL enhancement", column: "now", requiresTech: true, priority: "tbd" },
    { id: 39, title: "Welcome Call Flag", flag: "", theme: "5. DATA CAPTURE FOR FUTURE AUTOMATION", initiativeType: "CX", journeyStage: "Installation Occurs", description: "Technicians can flag customers who might need extra support-maybe they seemed confused or had questions.", implementation: "Flag in FSL", column: "now", requiresTech: true, priority: "tbd" },
    { id: 40, title: "Required Photo Checklist", flag: "", theme: "5. DATA CAPTURE FOR FUTURE AUTOMATION", initiativeType: "CX", journeyStage: "Installation Occurs", description: "A simple checklist that technicians must complete with photo evidence ensures consistent documentation.", implementation: "FSL checklist", column: "now", requiresTech: true, priority: "tbd" },
    { id: 41, title: "Guided Photo Capture", flag: "", theme: "5. DATA CAPTURE FOR FUTURE AUTOMATION", initiativeType: "CX", journeyStage: "Installation Occurs", description: "The app guides technicians through required photos step by step-can't proceed until photo is attached.", implementation: "FSL workflow", column: "now", requiresTech: true, priority: "tbd" },
    
    // 5. PROACTIVE COMMUNICATION AUTOMATION - in Scoping
    { id: 42, title: "Instant Change Alerts", flag: "Proactive touchpoints between sale and install", theme: "5. PROACTIVE COMMUNICATION AUTOMATION", initiativeType: "CX", journeyStage: "Sale Occurs", description: "If anything changes about the installation appointment, the customer is notified immediately.", implementation: "Event-triggered notifications", column: "scoping", requiresTech: true, priority: "tbd" },
    { id: 43, title: "1-Hour Arrival Alert", flag: "Ghosting", theme: "5. PROACTIVE COMMUNICATION AUTOMATION", initiativeType: "CX", journeyStage: "Installation is Booked", description: "Instead of a vague 5-hour window, customers get a notification about 1 hour before the technician arrives.", implementation: "FSL + SMS integration", column: "scoping", requiresTech: true, priority: "tbd" },
    { id: 44, title: "Cancellation Redirect to Live Agent", flag: "Nancy", theme: "5. PROACTIVE COMMUNICATION AUTOMATION", initiativeType: "CX", journeyStage: "Installation is Booked", description: "Update install confirmation SMS to route cancellation requests to a live agent phone call instead of allowing SMS cancel, to save appointments that could be rescheduled.", implementation: "SMS template update + routing", column: "scoping", requiresTech: true, priority: "tbd" },
    
    // 6. POST-INSTALL SUPPORT - QUICK WINS - in Scoping
    { id: 45, title: "Day 7/14 Check-In", flag: "Proactive touchpoints between sale and install", theme: "6. POST-INSTALL SUPPORT - QUICK WINS", initiativeType: "CX", journeyStage: "Account is Activated", description: "Automated text check-ins at day 7 and 14 catch small issues before they become big problems.", implementation: "Automated SMS", column: "scoping", requiresTech: true, priority: "tbd" },
    { id: 46, title: "Welcome Text", flag: "", theme: "6. POST-INSTALL SUPPORT - QUICK WINS", initiativeType: "CX", journeyStage: "Account is Activated", description: "Shortly after activation, a text welcomes the customer and provides an easy way to reach support.", implementation: "Automated SMS", column: "now", requiresTech: true, priority: "tbd" },
    { id: 47, title: "Enhanced Self-Help", flag: "", theme: "6. POST-INSTALL SUPPORT - QUICK WINS", initiativeType: "CX", journeyStage: "Account is Activated", description: "Enhanced online help resources-troubleshooting guides, video tutorials, FAQs-that help customers solve issues themselves.", implementation: "Knowledge base enhancement", column: "now", requiresTech: true, priority: "tbd" },
    { id: 48, title: "New Customer Priority Queue", flag: "", theme: "6. POST-INSTALL SUPPORT - QUICK WINS", initiativeType: "CX", journeyStage: "Account is Activated", description: "New customers calling support in their first 30 days get priority routing.", implementation: "Call routing rule", column: "now", requiresTech: true, priority: "tbd" },
    { id: 49, title: "New Customer IVR Welcome", flag: "", theme: "6. POST-INSTALL SUPPORT - QUICK WINS", initiativeType: "CX", journeyStage: "Account is Activated", description: "When new customers call support in the first 3 days, the IVR recognizes them with a special welcome.", implementation: "IVR configuration", column: "now", requiresTech: true, priority: "tbd" },
    { id: 50, title: "First 30 Days Gesture", flag: "", theme: "6. POST-INSTALL SUPPORT - QUICK WINS", initiativeType: "CX", journeyStage: "Account is Activated", description: "If a customer needs a service call in their first month, include a small gesture to acknowledge the inconvenience.", implementation: "Credit/gesture policy", column: "now", requiresTech: false, priority: "tbd" },
    
    // FEE LEAKAGE CARDS - in Prioritized Backlog
    { id: 51, title: "Credit Check", flag: "", theme: "", initiativeType: "Fee Leakage", journeyStage: "Sales Pre-Qual", description: "Implement credit check process to reduce bad debt and improve customer qualification.", implementation: "", column: "prioritized", requiresTech: false, priority: "high" },
    { id: 52, title: "Payment Upfront", flag: "", theme: "", initiativeType: "Fee Leakage", journeyStage: "Sales Pre-Qual", description: "Require payment upfront to reduce fee leakage and improve cash flow.", implementation: "", column: "prioritized", requiresTech: false, priority: "tbd" },
    { id: 53, title: "Buyer's Remorse", flag: "", theme: "", initiativeType: "Fee Leakage", journeyStage: "Sales Pre-Qual", description: "Address buyer's remorse issues to reduce early cancellations and fee leakage.", implementation: "", column: "prioritized", requiresTech: false, priority: "tbd" }
];
